@startuml Transparent_old_datastructure
Class ProjectReportTemplate{
- groups: Map<String, Group>     
}
Class Group{
- fields: Map<String, BaseInput>     
}
abstract Class BaseInput{
- type: Datatype     
- inputType: InputType
- modifiers: Set<InputModifier>
}
Class SingleInput{     
}
Class SelectSingleInput{
- allowedValues: List<Object>
}
Class MultiInput{    
}
Class SelectMultiInput{
- allowedValues: List<Object>     
}

BaseInput <|-- SingleInput
BaseInput <|-- SelectSingleInput
BaseInput <|-- MultiInput
BaseInput <|-- SelectMultiInput

ProjectReportTemplate "1" -- "1..*" Group
Group "1" -- "0..*" BaseInput
@enduml