@startuml Transparent_old_datastructure
Class ProjectReport{
- groups: Map<String, Group>
}
Class Group{
- fields: Map<String, BaseInput>
}
abstract Class BaseInput{
- type: Datatype
- inputType: InputType
- modifiers: Set<InputModifier>
}
Class SingleInputTemplate{
}
Class SelectSingleInputTemplate{
- allowedValues: List<Object>
}
Class MultiInputTemplate{
}
Class SelectMultiInputTemplate{
- allowedValues: List<Object>
}

Class SingleInput{
- value: Object
}
Class SelectSingleInput{
- value: Object
}
Class MultiInput{
- values: List<Object>
}
Class SelectMultiInput{
- values: List<Object>
}


BaseInput <|-- SingleInputTemplate
BaseInput <|-- SelectSingleInputTemplate
BaseInput <|-- MultiInputTemplate
BaseInput <|-- SelectMultiInputTemplate

SingleInputTemplate <|-- SingleInput
SelectSingleInputTemplate <|-- SelectSingleInput
MultiInputTemplate <|-- MultiInput
SelectMultiInputTemplate <|-- SelectMultiInput

ProjectReport "1" -- "1..*" Group
Group "1" -- "0..*" BaseInput
@enduml