package de.hhn.seb.labsw.transparentcockpit.backend.models.project.template.input;

import de.hhn.seb.labsw.transparentcockpit.backend.exceptions.validation.ValueException;
import de.hhn.seb.labsw.transparentcockpit.backend.models.project.base.input.BaseInput;
import de.hhn.seb.labsw.transparentcockpit.backend.models.project.base.input.DataType;
import de.hhn.seb.labsw.transparentcockpit.backend.models.project.base.input.InputModifier;
import de.hhn.seb.labsw.transparentcockpit.backend.models.project.base.input.InputType;
import de.hhn.seb.labsw.transparentcockpit.backend.models.project.util.ValidationUtil;

import java.util.Set;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Project Report InputTemplate of Type SingleInputTemplate.
 * SingleInput:
 * - Single Input Value
 */
public class SingleInputTemplate extends BaseInput {

    /**
     * Constructor.
     *
     * @param number    Number of the Input
     * @param name      Name of the Input
     * @param modifiers Modifiers of the Input
     * @param type      Type of the Input
     * @throws ValueException If something is wrong with the Value
     */
    public SingleInputTemplate(String number, String name,
                               Set<InputModifier> modifiers,
                               DataType type) throws ValueException {
        super(number, name, modifiers, type, InputType.SINGLE_INPUT);

        ValidationUtil.validateModifier(this.getClass().getName(), modifiers, InputModifier.AUTOGENERATED,
                InputModifier.REQUIRED, InputModifier.PROJECT_ID, InputModifier.PROJECT_NAME, InputModifier.PROJECT_GROUP);

    }

}