version: "3.9"

services:

  mongo:
    image: "mongo:5"

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: akten
      MONGO_INITDB_ROOT_PASSWORD: schredder

    volumes:
      - mongo_data:/data/db

    mem_limit: 2g

  mongo-express:
    image: "mongo-express"

    links:
      - mongo
    ports:
      - "8081:8081"

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: akten
      ME_CONFIG_MONGODB_ADMINPASSWORD: schredder
      ME_CONFIG_MONGODB_URL: mongodb://akten:schredder@mongo:27017/

    mem_limit: 2g


  postgres:
    image: "postgres:14"

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: aktenschredder
      POSTGRES_USER: akten
      POSTGRES_PASSWORD: schredder

    volumes:
      - postgres_data:/var/lib/postgresql/data

    mem_limit: 2g

  pgadmin:
    image: dpage/pgadmin4

    links:
      - postgres
    ports:
      - "8080:80"

    environment:
      PGADMIN_DEFAULT_EMAIL: akten@schredder.com
      PGADMIN_DEFAULT_PASSWORD: schredder


volumes:
  mongo_data:
  postgres_data:
