package de.hhn.seb.labsw.transparentcockpit.backend.models.project.base.input;

/**
 * Project Report Input Modifiers.
 * InputModifier witch the Backend Supports.
 */
public enum InputModifier {

  AUTOGENERATED,
  REQUIRED,

  DOUBLE_VALUE_ALLOWED,

  PROJECT_ID,
  PROJECT_NAME,
  PROJECT_GROUP

}
