name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - "**.puml"

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Get changed UML files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD | grep .puml | xargs)"

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg ${{steps.getfile.outputs.files}}
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: "Faroesne"
          commit_user_email: "faroesne@stud.hs-heilbronn.de"
          commit_author: "Fabian Rösner <faroesne@stud.hs-heilbronn.de>"
          commit_message: "Generate SVG and PNG images for PlantUML diagrams" 
          branch: ${{ github.head_ref }}
